variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - generate
  - trigger

generate:
  stage: generate
  tags:
    - shell
    - quartz
  script:
    - .radiuss-ci/gitlab/umpire/generate.sh
  artifacts:
    paths:
      - radiuss-*.yml

trigger:umpire-ci:
  stage: trigger
  trigger:
    include:
      - artifact: radiuss-*.yml
        job: generate
    strategy: depend
