
variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - date

after_script:
  - date

stages:
  - build
  - test

build_quartz_clang:
  tags:
    - shell
    - quartz
  stage: build
  variables:
    CLUSTER: "toss_3_x86_64_ib"
    COMPILER: "clang_3_9_1"
  script:
    - mkdir build_${CLUSTER}_${COMPILER}
    - cd build_${CLUSTER}_${COMPILER}
    - export CCONF=host-configs/${CLUSTER}/${COMPILER}.cmake 
    - cmake -C ../radiuss-ci-config/${CCONF} -C ../${CCONF} ..
    - cmake --build .
    - make test

build_quartz_gcc:
  tags:
    - shell
    - quartz
  stage: build
  variables:
    CLUSTER: "toss_3_x86_64_ib"
    COMPILER: "gcc_4_9_3"
  script:
    - mkdir build_${CLUSTER}_${COMPILER}
    - cd build_${CLUSTER}_${COMPILER}
    - export CCONF=host-configs/${CLUSTER}/${COMPILER}.cmake 
    - cmake -C ../radiuss-ci-config/${CCONF} -C ../${CCONF} ..
    - cmake --build .
    - make test

