trigger:quartz:
  trigger:
    include:
      - local: gitlab/quartz.yml
      - local: gitlab/child-pipeline.yml
    strategy: depend

trigger:lassen:
  trigger:
    include:
      - local: gitlab/lassen.yml
      - local: gitlab/child-pipeline.yml
    strategy: depend

trigger:build:
  trigger:
    include:
      - local: gitlab/butte.yml
      - local: gitlab/child-pipeline.yml
    strategy: depend
