##############################################################################
# Copyright (c) 2016-19, Lawrence Livermore National Security, LLC and Umpire
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_QUARTZ_ALLOC_NAME: "umpire_ci_build_on_quartz"

before_script:
  - date

after_script:
  - date

# There are no tests for now
stages:
  - allocate_resources
  - build
  - test
  - release_resources

# This is not a job, but contains project specific build commands
# If an allocation exist with the name defined in this pipeline, the job will use it
.build_quartz_script:
  script:
    - export JOBID=$(squeue -h --name=${BUILD_QUARTZ_ALLOC_NAME} --format=%A)
    - srun $( [[ -n "${JOBID}" ]] && echo "--jobid=${JOBID}" ) -t 10 -N 1 -n 1 -c 4 scripts/gitlab/build.sh
  artifacts:
    reports:
      junit:
        Test.xml

# Butte uses a very different job allocation system, building on login nodes is recommended
.build_butte_script:
  script:
    - lalloc 1 scripts/gitlab/build.sh


# This is where jobs are included
include:
  - local: .gitlab/ci/build_quartz.yml
  - local: .gitlab/ci/build_butte.yml


