
variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - date

after_script:
  - date

stages:
  - build
  - test

.build_script:
  script:
    - mkdir build_${CLUSTER}_${COMPILER}
    - cd build_${CLUSTER}_${COMPILER}
    - export CCONF=host-configs/${CLUSTER}/${COMPILER}.cmake 
    - cmake -C ../radiuss-ci-config/${CCONF} -C ../${CCONF} ..
    - srun -p pdebug -t 5 -N 1 -n 4 cmake --build -j 4 .
    - make test

build_quartz_clang:
  tags:
    - shell
    - quartz
  stage: build
  variables:
    CLUSTER: "toss_3_x86_64_ib"
    COMPILER: "clang_3_9_1"
  extends: .build_script

build_quartz_gcc:
  tags:
    - shell
    - quartz
  stage: build
  variables:
    CLUSTER: "toss_3_x86_64_ib"
    COMPILER: "gcc_4_9_3"

