
variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - date

after_script:
  - date

stages:
  - build
  - test

.build_script:
  script:
    - srun -p pdebug -t 10 -N 1 -n 1 -c 4 scripts/launch.sh

include:
  build-template.yml
