variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - generate
  - build

generate:
  stage: generate
  tags:
    - shell
    - quartz
  script:
    - .radiuss-ci/gitlab/umpire/generate.sh
  artifacts:
    paths:
      - radiuss-*.yml

trigger:umpire-ci:
  stage: build
  trigger:
    include:
      - artifact: child-pipeline.yml
        job: generate
      - artifact: quartz-template.yml
        job: generate
      - artifact: quartz-jobs.yml
        job: generate
      - artifact: lassen-template.yml
        job: generate
      - artifact: lassen-jobs.yml
        job: generate
      - artifact: butte-template.yml
        job: generate
      - artifact: butte-jobs.yml
        job: generate
    strategy: depend
