variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - generate
  - build

generate:
  stage: generate
  tags:
    - shell
    - quartz
  script:
    - .radiuss-ci/gitlab/umpire/generate.sh
  artifacts:
    paths:
      - radiuss-umpire-ci.yml

trigger:umpire-ci:
  stage: build
  trigger:
    include:
      - artifact: radiuss-umpire-ci.yml
        job: generate
    strategy: depend
