variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - generate
  - build

generate:quartz:
  stage: generate
  tags:
    - shell
    - quartz
  script:
    - .radiuss-ci/gitlab/umpire/generate.sh quartz
  artifacts:
    paths:
      - child-pipeline.yml
      - quartz-template.yml
      - quartz-jobs.yml

generate:lassen:
  stage: generate
  tags:
    - shell
    - quartz
  script:
    - .radiuss-ci/gitlab/umpire/generate.sh lassen
  artifacts:
    paths:
      - child-pipeline.yml
      - lassen-template.yml
      - lassen-jobs.yml

generate:butte:
  stage: generate
  tags:
    - shell
    - quartz
  script:
    - .radiuss-ci/gitlab/umpire/generate.sh butte
  artifacts:
    paths:
      - child-pipeline.yml
      - butte-template.yml
      - butte-jobs.yml

trigger:quartz:
  stage: build
  trigger:
    include:
      - artifact: child-pipeline.yml
        job: generate:quartz
      - artifact: quartz-template.yml
        job: generate:quartz
      - artifact: quartz-jobs.yml
        job: generate:quartz
    strategy: depend

trigger:lassen:
  stage: build
  trigger:
    include:
      - artifact: child-pipeline.yml
        job: generate:lassen
      - artifact: lassen-template.yml
        job: generate:lassen
      - artifact: lassen-jobs.yml
        job: generate:lassen
    strategy: depend

trigger:butte:
  stage: build
  trigger:
    include:
      - artifact: child-pipeline.yml
        job: generate:butte
      - artifact: butte-template.yml
        job: generate:butte
      - artifact: butte-jobs.yml
        job: generate:butte
    strategy: depend
